### ISSUE TITLE
Snippet wrongly blocked as 'terminal has exited' on a live terminal after right-click Restart

### ISSUE THREAD

**Issue by justi** [khasinski/aya#23]
## Problem

Clicking a saved snippet in the drawer prints

    aya: terminal has exited — press Shift+Enter to restart, then send the snippet again

into the terminal instead of sending the snippet — even though the terminal is alive and accepting input. Switching to another pane/terminal and back makes it work again.

Note: there is only one snippet send path — both autoRun ("run") and hold ("type"/insert) snippets go through onSend -> sendSnippet, so both are blocked identically.

## Root cause

There are two layers here. Treating only the first leaves the design that produces it untouched.

### Proximate cause — a kill/respawn race

sendSnippet (src/components/TerminalView.tsx) refuses to write whenever terminal.exitCode !== null and prints that notice instead. forceRestartTerminal (src/App.tsx, the right-click -> Restart handler):

1. await window.aya.ptyKill(id) kills the PTY.
2. setTerminals resets exitCode to null, then setRestartTriggers respawns a fresh PTY with the same id.
3. The kill's asynchronous child.onExit (electron/pty.ts) fires and emits an exit event for that id AFTER step 2, so the reducer (src/pty-event-reducer.ts) re-sets exitCode to a non-null value — now on the freshly respawned, alive PTY.

From then on terminal.exitCode is stuck non-null even though the PTY is alive (the terminal keeps rendering because TerminalView writes incoming data unconditionally, with no exitCode check). Switching panes remounts/respawns and clears the stale state, which is why it "fixes itself".

### Root cause — terminalId and ptyId are the same value, reused across PTY generations

The race is a symptom. The root is an identity conflation: one identifier carries two responsibilities at once —

- a stable UI slot (this terminal, its scrollback, sidebar position, snippet drawer), and
- the identity of a concrete OS process (a PTY instance that is born and dies).

Because the id is reused on spawn -> kill -> respawn, there is no notion of a process "generation"/lifecycle, so an exit event from a dead generation is indistinguishable from a live one. Any fix that copes with a stale event for a reused id is treating this conflation.

## Fix directions (scope decision for the maintainer)

- Source-side suppression (skip the exit emit for intentionally-killed children): smallest diff, but it entrenches the design — masks the symptom with a hidden side-channel and leaves the root in place, so the bug class can resurface. Not recommended as the real fix.
- Epoch / fencing token (the exit event carries a per-id generation; the reducer ignores stale generations): a principled, well-known pattern, and it makes the ignore-logic a pure unit-testable reducer — but it only exists because the id is reused. A good band-aid, not a root fix. If chosen, pair it with an ADR/comment stating it is a workaround for the id conflation.
- Decouple identity (stable terminalId for the UI slot + a fresh ptyInstanceId per spawn): the only option that removes the root — a stale exit references a dead instance id that maps to no live terminal, so it is naturally inert. No epoch, no suppression; the whole bug class becomes structurally impossible. Larger blast radius (spawn request, the ptys map keys, write/resize/kill, the event ptyId, the detached pty-host, and the renderer's terminal->pty mapping).

Regardless of direction, one correctness guard belongs in any fix: an old child's onExit must not delete the new child from the ptys map (only delete when ptys.get(id) is still that child).

@khasinski — this touches the core PTY subsystem, so the scope is your call: the minimal epoch + ADR, or the proper decouple-identity refactor you may prefer to design yourself.

## Reproduction

Deterministic e2e in PR #24 / branch test/snippet-exited-terminal-repro (e2e/snippet-exited-terminal.spec.ts), reproduces 3/3 with --repeat-each:

- right-click a sidebar terminal -> Restart terminal
- confirm the terminal is alive (a typed echo marker comes back)
- click a snippet -> the "has exited" notice appears instead of the snippet being sent

The test asserting the correct behaviour (no notice on a live terminal) is marked test.fail() so CI stays green while the bug is open; removing test.fail() flips it green once the race is fixed.

## Why no existing test caught it

The snippet e2e (e2e/snippets.spec.ts) only covers the happy path (live terminal, snippet sent). The sendSnippet exitCode guard branch had zero coverage. The reducer test covers exit -> exitCode in isolation but never the kill+respawn race or the snippet interaction.

## Environment

- Platform: macOS
- Affects: any terminal restarted via right-click -> Restart (forceRestartTerminal)

**Comment by justi** [comment]
## Deeper root cause (architectural) — for @khasinski to weigh in on scope

On reflection the forceRestartTerminal kill/respawn race is the *symptom*, not the root cause. The root is an identity conflation:

**terminalId and ptyId are the same value, reused across PTY process generations.**

One identifier carries two responsibilities at once:
- a stable UI slot (this terminal, its scrollback, sidebar position, snippet drawer)
- the identity of a concrete OS process (a PTY instance that is born and dies)

Because the id is reused on spawn -> kill -> respawn, there is no notion of a process "generation" or lifecycle, so an exit event from a dead generation is indistinguishable from a live one. Any fix that copes with a stale event for a reused id is treating this conflation.

### How the fix options relate to the architecture

- **Source-side suppression** (a WeakSet of intentionally-killed children that skips the exit emit): smallest diff, but it entrenches the design — it masks the symptom with a hidden side-channel, leaves the root in place, and the same class of bug can resurface. I would not ship this as the real fix.
- **Epoch / fencing token** (the exit event carries a per-id generation; the reducer ignores stale generations): a principled, well-known pattern, and it makes the ignore-logic a pure unit-testable reducer — but it only exists because the id is reused. It is a good band-aid, not a root fix.
- **Decouple identity** (stable terminalId for the UI slot + a fresh ptyInstanceId per spawn): the only option that removes the root. A stale exit references a dead instance id that maps to no live terminal, so it is naturally inert — no epoch, no suppression, the whole bug class becomes structurally impossible.

One piece is correct regardless of which direction you pick: an identity guard on cleanup so an old child's onExit cannot delete the *new* child from the ptys map (only delete when ptys.get(id) is still that child).

### Decision for the maintainer

Decoupling is the architecturally correct fix, but it touches the core PTY subsystem (spawn request, the ptys map keys, write/resize/kill, the event ptyId, the detached pty-host, and the renderer's terminal->pty mapping) — real regression surface. As a contributor I do not want to parachute a core refactor without your call.

@khasinski — how would you like to scope this?
1. Minimal now: epoch token + an ADR/comment that explicitly states it is a workaround for the terminalId/ptyId conflation (so the band-aid does not silently pretend to be a solution), or
2. The proper fix: decouple terminalId from ptyInstanceId, which you may prefer to design yourself.

The reproduction (PR #24, currently test.fail) verifies whichever direction lands — removing test.fail() flips it green.

**Comment by khasinski** [comment]
Update: the user-visible bug is fixed on main.

The fix landed in 510f96e and is still covered after the later E2E hardening:
- old PTY child onExit is fenced so it cannot delete/mark the newly respawned PTY for the same terminal id
- e2e/snippet-exited-terminal.spec.ts now runs as a normal passing regression, not test.fail
- latest validation is green: local npm test 236/236, local E2E 31/31, and CI run https://github.com/khasinski/aya/actions/runs/26983045964 is green

This does not implement the larger terminalId/ptyInstanceId decoupling described above. My recommendation is to close this issue for the snippet/restart symptom and open a separate architecture ticket for PTY instance identity. If we keep this one open, it should be retitled to that architecture work; otherwise the title is now misleading.

**Comment by justi** [comment]
This looks resolved on main. The regression guard from #24 — `e2e/snippet-exited-terminal.spec.ts` → *"snippet on a restarted (alive) terminal is not blocked as 'exited'"* — passes on current main: after right-click → Restart the terminal is alive and a snippet sends normally, with no "terminal has exited" notice.

I verified locally that the original repro no longer reproduces (bug was deterministic 3/3 when I filed the repro; now it does not fire). The guard lives on main, so a regression would be caught in CI.

Transparency caveat: I didn't spot a dedicated race-fix commit, so this may be a structural fix or it may be that the kill→respawn timing now resolves favourably — either way the regression test is the safety net.

Related: #32 (open) hardens that same test so it stops false-failing on non-$/%/# shell prompts (arrow / powerline), which makes the guard reliable for contributors locally.

@khasinski — if you agree it's resolved, this can be closed.
